# Generated by Django 5.2.5 on 2026-05-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_category_unique_together_category_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
    ]
