# Generated by Django 5.2.5 on 2026-05-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_income_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='payment_info',
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentInfo',
        ),
    ]
