# Generated by Django 5.2.5 on 2026-05-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_expense_payment_info_expense_payment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='category',
        ),
    ]
