# Generated by Django 5.2.5 on 2026-05-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_debt_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='profiles',
        ),
    ]
