# Generated by Django 5.2.5 on 2026-05-09 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_debt_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='profiles',
        ),
        migrations.AddField(
            model_name='income',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='income_distributions', to='api.profile'),
            preserve_default=False,
        ),
    ]
