from django.urls import path

from .views import (
    RegisterView,
    LoginView,
    LogoutView,
    ProfileView,
    ProfileDetailView,
    ProfileSummaryView,
    ProfileMonthlyView,
    ProfileMonthlyDetailView,
    ProfileExpensesView,
    ProfileExpensesDetailView,
    CategoryView,
    CategoryDetailView,
    ExpenseView,
    ExpenseDetailView,
    IncomeView,
    IncomeDetailView,
    DebtView,
    DebtDetailView,
    DashboardView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('profiles/', ProfileView.as_view(), name='profiles'),
    path('profiles/<int:pk>/', ProfileDetailView.as_view(), name='profile-detail'),
    path('profiles/<int:pk>/summary/', ProfileSummaryView.as_view(), name='profile-summary'),
    path('profiles/<int:pk>/monthly/', ProfileMonthlyView.as_view(), name='profile-monthly'),
    path('profiles/<int:pk>/monthly/<int:year>/<int:month>/', ProfileMonthlyDetailView.as_view(), name='profile-monthly-detail'),
    path('profiles/<int:pk>/expenses/', ProfileExpensesView.as_view(), name='profile-expenses'),
    path('profiles/<int:pk>/expenses/<int:exp_pk>/', ProfileExpensesDetailView.as_view(), name='profile-expense-detail'),
    path('categories/', CategoryView.as_view(), name='categories'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('expenses/', ExpenseView.as_view(), name='expenses'),
    path('expenses/<int:pk>/', ExpenseDetailView.as_view(), name='expense-detail'),
    path('incomes/', IncomeView.as_view(), name='incomes'),
    path('incomes/<int:pk>/', IncomeDetailView.as_view(), name='income-detail'),
    path('debts/', DebtView.as_view(), name='debts'),
    path('debts/<int:pk>/', DebtDetailView.as_view(), name='debt-detail'),
]
